name: "JFrog CLI Example"
 
on:
   pull_request:
     branches: 
      - FaiqueAli-patch-1
   push:
      branches: 
       - main
       - FaiqueAli-patch-1


jobs:

  lint:
    runs-on: self-hosted
    #ubuntu-latest    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history  
        
      - name: update git tag
        run: ."C:\Program Files\Git\bin\bash.exe" ./tag-release.sh --branch FaiqueAli-patch-1 --message first-version-from-workflow --type build

      - name: Upload binaries to release
        uses: actions/upload-artifact@v3
        with:
         name: v-gitactionrepo
         path: module1
         #v0.0.0.2 test 


          

  build:
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, dso-codeql-win]
    steps:
       - name: Test Selfhosted Docker container
         run: echo 'echo from debian'
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Setup JFrog CLI
#         uses: jfrog/setup-jfrog-cli@v1
#         env:
#           JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
#       - name: Run JFrog CLI
#         run:  |
#            jfrog --version
#            jfrog rt ping
#            # Collect environment variables for the build
#            jfrog rt bce
#            # Collect VCS details from git and add them to the build
#            jfrog rt bag
#            # Publish build info
#            jfrog rt bp
           
         
#            echo ${{ github.event_name }}
#            echo ${{ github.ref_name }}
#            echo ${{ github.ref }}
#       #- uses: actions/upload-artifact@v2
#       #- name: upload artifacts       
#       #  run:  jfrog rt u jftest.zip myconanrepo
        
#       #- name: Download artifact 
#       #  run: jfrog rt dl myconanrepo/jftest.zip
#       - name: Download a single artifact
#         if: github.event_name == 'push' && github.ref_name == 'main'
             
#         uses: actions/download-artifact@v1
#         with:
#          name: jftest.zip

