name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}
      - name: Run JFrog CLI
        run:  |
           jfrog --version
           jfrog rt ping
           # Collect environment variables for the build
           jfrog rt bce
           # Collect VCS details from git and add them to the build
           jfrog rt bag
           # Publish build info
           jfrog rt bp
      
      #- uses: actions/upload-artifact@v2
      #- name: upload artifacts       
      #  run:  jfrog rt u jftest.zip myconanrepo
        
      #- name: Download artifact 
      #  run: jfrog rt dl myconanrepo/jftest.zip
      - name: Download a single artifact
        uses: actions/download-artifact@v1
        with:
         name: jftest.zip
