name: "JFrog CLI Example"
on: push


jobs:
  lint:
    runs-on: self-hosted
    #ubuntu-latest    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history  
        
      - name: update git tag
        run: ."C:\Program Files\Git\bin\bash.exe" ./tag-release.sh --branch FaiqueAli-patch-1 --message first-version-from-workflow --type build

      - name: Upload binaries to release
        uses: actions/upload-artifact@v3
        with:
         name: v-gitactionrepo
         path: module1
         #3.0.0.7 to 3.0.1.0 

          
